### PR TITLE
Ru translation

### PR DESCRIPTION
**Pull request by kysokzla**
Little fixes
P.S. 
I'm back :-)

### CODE REVIEW

**Comment by commjoen** [comment]
Good to have you back! Can I ask you a favor? can you help out @emartynov at https://github.com/OWASP/owasp-masvs/issues/322 ? so we can finalize the russian translation at the MASVS?

**Comment by cpholguera** [comment]
Hi @kysokzla and welcome back :) we'd love to keep a good track of the progress of the translation. Would it be ok for you if you only include the updated or newly fully translated files in this PR? That would help us a lot when reviewing.

Now's a bit hard to tell, also mostly because somehow all files in the repo show up as they've been touched :/ did you have any merging problems? We can gladly support you if you need some help.

Thank you very much :)

**Comment by kysokzla** [comment]
Hi @cpholguera first Russian translation was entirely made by me with help of my collegues it was only 0x06 chapters(iOS parts). I have not got much time this year, but i made some typos and rewords. Also i have merged all of the english missing files in order to live translate and other guys could easily colloborate on this cause it could be runglish texts(one part, for example would be in russian but other in english - would commit and others could finish my work). 
I think it's good practice, so my pr is about fixing my own errors that i've spotted during work. And also new files. I'm going to ask my Android friends to make Android part or i\ll do it myself step by step. 
Thanks in advance.

**Comment by kysokzla** [comment]
@commjoen  i've reviewed this and commented out about changelog. But to make this document up-to-date with english version requires some time. Maybe next week or two weeks from now.

**Comment by emartynov** [comment]
@kysokzla I believe something wrong happened with the merge of the master. As for now, your MR has touched 431 files instead of 0x06 chapters.

**Comment by cpholguera** [comment]
Hi @kysokzla , sure, that's totally fine ^^ Just as @emartynov mentioned, I also think something went wrong with the merge. I suggest getting a new branch from the current master and copying over the files you know you've modified. This way we can be sure that everything is right and in place. And again, if you need any support just let us now. We're glad to help :)

Thanks again!

**Comment by kysokzla** [comment]
@emartynov could u provide some detailed info please? I pulled the master and was behind it by my 5 commits? I've added english version of the files to the Document-ru and that is it. As i told it was made for convinience. And before merge i double checked everything.
I need some details what is wrong

**Comment by kysokzla** [comment]
I could spot only some weird diff with images ill check it but i think they are the same only creation timestamp changed. Any help would be great. About other files if u click on diff many of them state NO changes.

**Comment by kysokzla** [comment]
So @emartynov  @cpholguera  i think u should really double check my PR, because i did it. It's weird but this is how git works, i synced my fork and pulled from remote origin. that is it. i dunno why i should destroy my local repo and revert back and forth my uncommited changes. Any help would be great.
Снимок экрана 2019-10-29 в 7 43 43

**Comment by emartynov** [comment]
As was suggested - instead of trying to fix the current branch - you can just create a new one from latest master and cherry-pick your commits from this branch with your changes.

**Comment by sushi2k** [comment]
Hi @kysokzla. Any update on when you can make the changes to the PR? Please follow the suggestions from @commjoen to start small and then we can merge piece by piece on what was translated. Thanks for your support!

**Comment by sushi2k** [comment]
This PR is getting closed, as it contains the whole english translation and is only partially translated in Russian.

**Pull request closed without merging**
