### PR TITLE
Intro to Bytecode Viewer

### PR DESCRIPTION
**Pull request by su-vikas**
For #1704 

- Added intro for Bytecode Viewer. 
- Fixed byte-code to bytecode
- Update style guide for "bytecode".

### CODE REVIEW

**Review by cpholguera — COMMENTED** [review]
Hi @su-vikas, thanks for these changes. If you don't mind we'll apply them after PR #1843, we hope to be able to merge it soon (this or next week)

**Comment by cpholguera** [comment]
Hi @su-vikas! PR #1843 is finished finally, please take a look at the new structure in 0x08. Could you please do `git pull origin master` and move "Bytecode Viewer" over there? it should go in section "## Tools for Android" (please beware the alphabetical order). If possible, please also link back to it from the testing chapter where it's mentioned: `[Bytecode Viewer](0x08-Testing-Tools.md#bytecode-viewer)`

Thank you in advance!

**Comment by su-vikas** [comment]
@cpholguera The new structure looks much better to me, also a good point of quick reference for tools. 

I have added the bytecode viewer description to it, let me know if its okay.

**Review by cpholguera — CHANGES_REQUESTED** [review]
Awesome @su-vikas, there's only one thing to restore and one suggestion. thanks!

**Comment by su-vikas** [comment]
@cpholguera  done :).

**Review by cpholguera — APPROVED** [review]
Awesome, thanks again @su-vikas!

**Pull request merged**
