### PR TITLE
0x04e - About OTP Authentication Checks

### PR DESCRIPTION
**Pull request by Saket-taneja**
Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

### CODE REVIEW

**Comment by Saket-taneja** [comment]
@cpholguera Hey Buddy any updates on this ?

**Comment by cpholguera** [comment]
Hi @Saket-taneja, thanks for reaching out! We'll address more PRs in the upcoming year. As you might know we're in the middle of a big refactoring for the MASVS which will extend to the MSTG. We were also improving our pipelines so that we can release more often. Thanks for your patience and congratulations for making it to our list of New Contributors! 🎉

**Review by cpholguera — CHANGES_REQUESTED** [review]
Hi @Saket-taneja, thanks a lot for your PR and sorry for the late response from our side. We had to give more priority to the [MASVS refactoring](https://github.com/OWASP/owasp-masvs/discussions/553) process and we are still working on it.

Here are a couple of suggested changes, if you like them you can click on the button "Commit suggestion" and they'll be integrated. Thanks a lot for the PR and for your patience!

**Review by cpholguera — APPROVED** [review]
Thanks a lot @Saket-taneja for your contribution and your patience. We're ready to go!

**Pull request merged**
