### PR TITLE
Change gendered language regarding users and testers to be neutral

### PR DESCRIPTION
**Pull request by grenlith**
This was done while ensuring grammatical consistency, and will be less awkward in some situations to read than the longer and more ambiguous "he or she".
Each change was manually reviewed.

Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR covers issue #< insert number here >.

### CODE REVIEW

**Comment by commjoen** [comment]
Hi @grenlith , thank you very much for your PR! We are looking into this as rewriting it will take much more than the noted 19 changes and will be very extensive! We are currently working on a lot of other things as well, so I guess we can better start with an issue to discuss it, would you mind filing one instead? Using they is one of the 9 gender-neutralizing ways, but plural can be very confusing to me as well. Let's do a little more processing apriori :)

**Comment by grenlith** [comment]
It honestly really doesn't take much more than the pull request, even though I missed a couple of instances, and in English 'they' was singular before 'you' was. I was just trying to bring a few instances in very specific sections in to line with the rest of the text.

I apologize, but I don't have the time to open an issue and debate the use of singular they, and I hope you do include these changes in future versions. There are a lot of non-men in security, and it's alienating to read a text that assumes otherwise.

**Comment by commjoen** [comment]
hi @grenlith , obviously we don't want the text to exclude anyone! Whether woman, man or non-binary people: evyerbody should be able to use the guide without getting frustrated. I will file an issue and keep a link to this pr so we can make this work for everyone!

**Comment by commjoen** [comment]
Issue filed under #1534, we will surely pick this up

**Pull request closed without merging**
