### PR TITLE
0x05c Android tooling updated

### PR DESCRIPTION
**Pull request by su-vikas**
For issue #1363. 

Added content to Frida and Xposed sub section to Tooling. Most of the details are already covered in the other parts of the guide, just referred to existing content.

### CODE REVIEW

**Comment by cpholguera** [comment]
Hi @su-vikas , you're right! And that made me think: the info/overview/intro to the tools is scattered thoughout the guide but we actually have a "Tools" chapter. What if we pack all intros there and simply refer to that section? That has many advantages:
- No repetition.
- One unique place for all tools.
- The Test Cases will only contain "actions" we make using those tools.
- We can even build an overview of where a tools is being used using a parsing script.

What do you think? 

@sushi2k and you?

**Comment by cpholguera** [comment]
UPDATE: I got inspired and I will be opening a PR for this very soon. I'm moving all the tool descriptions to the Tools chapter and will refere back there from the rest of the guide. In that PR I'm removing the "Tooling" section of in 0x6c after "Dynamic Instrumentation". Therefore, we can close this one. But I might need your help @su-vikas when I open the other PR, is that ok for you? Thanks a lot for getting attention to this topic again ^^

**Comment by cpholguera** [comment]
Opened PR: https://github.com/OWASP/owasp-mstg/pull/1843

**Comment by su-vikas** [comment]
@cpholguera  totally agree with this approach. This makes referring to the guide for learning about tools easier too. And sure I can help with the new PR.

**Pull request closed without merging**
