### PR TITLE
[QA] Fixed method names as per style guide

### PR DESCRIPTION
**Pull request by cpholguera**
This PR fixes all method names removing all parenthesis to comply with our style guide.

NO CONTENT WAS CHANGED.

### CODE REVIEW

**Comment by OMTGreleaser** [comment]
Results for commit cf11742489c8c25146015344b43f3de3e3d7b405: Broken link result: [!] Error(s) found by the Links validator: 4 pages have dead links! Verbose output in /link-check-result.out .
 Please run the Apply_Link_Check.sh in the tools folder to see wherhe the Link issues are. 
 Markdown result errorlength:        7 ../linter-result.out .
 Please run the Apply_Linter_check.sh in the tools folder to see where the Lint issues are.

**Comment by commjoen** [comment]
Merging is pending on a conflict in Document/0x06h-Testing-Platform-Interaction.md, can you merge in master and resolve the conflict please?

**Comment by cpholguera** [comment]
conflict fixed ;)

**Comment by commjoen** [comment]
new conflicts due to previous merge. can you resolve them please?

**Comment by cpholguera** [comment]
done ;)

**Comment by commjoen** [comment]
thanks!

**Pull request merged**
