### PR TITLE
Ensure that tiles are in sync on Excel and MSTG #1388

### PR DESCRIPTION
**Pull request by A-AFTAHI**
Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR covers issue #< insert number here >.

### CODE REVIEW

**Comment by cpholguera** [comment]
the titles are in sync with tag 1.1.2 of the MSTG, is that the intention? Some have changed in the current master after the restructuring.

**Comment by cpholguera** [comment]
if that was the intention I've verified the iOS links+titles and they're all correct.

**Comment by commjoen** [comment]
Can we merge this one and then create another one when we tagged master with 1.1.3? Makes sense to me

**Comment by cpholguera** [comment]
Sounds good to me as well 👍

**Comment by A-AFTAHI** [comment]
you'e welcome!

**Pull request merged**
