### PR TITLE
less_noise: attempt to make feedback a little cleaner

### PR DESCRIPTION
**Pull request by commjoen**
Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

This PR improves the feedback provided by the system for those who have write access to the repo.

### CODE REVIEW

**Comment by OMTGreleaser** [comment]
Results for commit 61702ed2a2832890021397fc0fd7fbda9cd4927a: 
 Broken link result: [!] Error(s) found by the Links validator: 2 pages have dead links! Verbose output in /link-check-result.out, 
 markdown result errorlength:       22 ../linter-result.out. 
 If fields are empty or 0: you should be OK. If fields contain data: please check for markdown and link errors.

**Comment by OMTGreleaser** [comment]
Results for commit 61702ed2a2832890021397fc0fd7fbda9cd4927a: 
 Broken link result: [!] Error(s) found by the Links validator: 1 pages have dead links! Verbose output in /link-check-result.out, 
 markdown result errorlength:       22 ../linter-result.out. 
 If fields are empty or 0: you should be OK. If fields contain data: please check for markdown and link errors.

**Comment by commjoen** [comment]
Note: new instructions will only kick in once on master :).

**Comment by OMTGreleaser** [comment]
Results for commit c992303292f5bb3f62acc23c0be5cbf4d467b457: Broken link result: [!] Error(s) found by the Links validator: 1 pages have dead links! Verbose output in /link-check-result.out .
  
 Markdown result errorlength:       22 ../linter-result.out .

**Comment by OMTGreleaser** [comment]
Results for commit 35f6526a132f0ccbb3b1531610346e99047a495c: Broken link result: [!] Error(s) found by the Links validator: 1 pages have dead links! Verbose output in /link-check-result.out .
  
 Markdown result errorlength:       22 ../linter-result.out .

**Comment by OMTGreleaser** [comment]
Results for commit 12a28359d57cf8033f9dddb280decf286bb591c3: Broken link result: [!] Error(s) found by the Links validator: 2 pages have dead links! Verbose output in /link-check-result.out .
 Please run the Apply_Link_Check.sh in the tools folder to see wherhe the Link issues are. 
 Markdown result errorlength:       22 ../linter-result.out .
 Please run the Apply_Linter_check.sh in the tools folder to see where the Lint issues are.

**Comment by OMTGreleaser** [comment]
Results for commit c76dcaeb069dbf1f61c6c1f6a2dee87f6aa9543d: Broken link result: [!] Error(s) found by the Links validator: 1 pages have dead links! Verbose output in /link-check-result.out .
 Please run the Apply_Link_Check.sh in the tools folder to see wherhe the Link issues are. 
 Markdown result errorlength:       22 ../linter-result.out .
 Please run the Apply_Linter_check.sh in the tools folder to see where the Lint issues are.

**Pull request merged**
