### PR TITLE
Update 0x04f-Testing-Network-Communication.md

### PR DESCRIPTION
**Pull request by silkychoudhary**
Added MiTM Proxy Tools - For instance, this can be used to write the encryption logics implemented on the APIs such that plain text traffic can be captured in Burp Suite

Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

### CODE REVIEW

**Comment by sushi2k** [comment]
Hi @silkychoudhary. Thanks for adding. We only want to add additional tools that we are also using in the guide. Can you elaborate the use case you are mentioning? Can't this also be done through a burp extension in Burp Suite?
Are you talking about End2End encryption being used between the Mobile App and the API?

**Comment by silkychoudhary** [comment]
Hi @sushi2k,

Yes, correct. Not all encryption can be bypassed using the burp extension and few of the extensions requires manual intervention. As an analyst, we need to reverse engineer the app, understand the typical encryptions and automate them in the upstream/downstream proxy so that plain text traffic can be captured in burp and further be manipulated.

**Comment by cpholguera** [comment]
Hi @silkychoudhary, could you please find an appropriate place in the guide to explain this? I you could add a couple of lines explaining the problematic and the proposed solutions and recommended tools we can add them in the "tools" section. Thanks a lot!

**Comment by cpholguera** [comment]
Hi @silkychoudhary we'll close the PR for now. We can reopen it if you'd like to add that content or just open a new one. Please contact us here or on slack if you have any questions. Thanks a lot 😊

**Pull request closed without merging**
