### PR TITLE
Update 0x05e-Testing-Cryptography.md

### PR DESCRIPTION
**Pull request by mkaraoz**
added a note for elliptic curves.

Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

### CODE REVIEW

**Review by cpholguera — CHANGES_REQUESTED** [review]
Thanks for the addition @mkaraoz , could you please include an inline link to the specific part of the docs as a reference for that?

**Comment by mkaraoz** [comment]
> Thanks for the addition @mkaraoz , could you please include an inline link to the specific part of the docs as a reference for that?

I dont think I can. Documentation does not say that directly but when you check the available ciphers there is no EC (https://developer.android.com/guide/topics/security/cryptography#SupportedCipher) 

Also, according to this [stackoverflow post](https://stackoverflow.com/a/57634295/891194) it is not supported. The guy who wrote the answer (Shawn Willden) is the Google engineer who owns AndroidKeyStore. 

I can link these two sources if you like.

**Comment by cpholguera** [comment]
The first one should be enough, thanks a lot!

https://developer.android.com/guide/topics/security/cryptography#SupportedCipher

**Review by cpholguera — APPROVED** [review]
Thanks again @mkaraoz!

**Pull request merged**
