### PR TITLE
Update mlc_config.json

### PR DESCRIPTION
**Pull request by cpholguera**
allow only code 200 for alive

### CODE REVIEW

**Comment by cpholguera** [comment]
any ideas on what to do with the 403s @anantshri?

**Comment by anantshri** [comment]
@cpholguera my suggestion would be to keep adding domains in the ignore pattern for now. till the list is now growing above 100 entries. 

If it does that cross it then we think of something else. a possible logic could be look for 403 with cloudflare in text then its okey if not then raise a flag.

**Comment by cpholguera** [comment]
ok. Thanks for the feedback @anantshri . But we really need to come up with a solution for this. It's very disturbing for contributors and for us always having to explain that it's ok that this check fails.

I'll enable the option to only check changed files for PRs. This should improve the experience, if someone's introducing a new dead link it will be reported. If it's not dead, the contributors have to add the exceptions themselves to this list. This will be of course documented.

For now I'll add these to the list:

https://www.verticalstructure.com
 https://support.virustotal.com/hc/en-us/articles/115002146549-Mobile-Apps

**Comment by anantshri** [comment]
Just a note https://github.com/tcort/markdown-link-check/issues/109 is the issue in markdown-link-check which should sort this out eventually.

**Comment by cpholguera** [comment]
Great, thanks for checking that @anantshri, very helpful!

**Review by sushi2k — APPROVED** [review]

**Comment by sushi2k** [comment]
Thank you for the workaround @cpholguera and @anantshri!

**Pull request merged**
