### PR TITLE
Added QuickJS for Frida 14.0, Objection, etc.

### PR DESCRIPTION
**Pull request by raulsiles**
Brief quick review just of the Frida section...: Added QuickJS for Frida 14.0, Objection, fixed typos, etc.

### CODE REVIEW

**Comment by cpholguera** [comment]
Hola Raul, nice to hear from you and thanks for the update! We're currently restructuring the whole "Tools" topic and moving everything to the Tools chapter, you can see that in PR #1843 . I've added the quickjs detail for Frida but the rest of your modifications should be also added. If you don't mind we can integrate them once we have that other PR merged? It might be only a matter of applying the same changes but somewhere else.

Cheers,
Carlos

**Comment by raulsiles** [comment]
Hi there.
Yes, feel free to re-add all changes once the full Tools PR has been merged. 
Thanks.
--
Raul Siles

**Comment by cpholguera** [comment]
Hi @raulsiles, the PR #1843 is ready, this Frida section is located now in https://github.com/OWASP/owasp-mstg/blob/master/Document/0x08-Testing-Tools.md#frida 

Would you like to re-apply your changes over there, or should we do it? Thank you!

**Review by newblaque — APPROVED** [review]

**Comment by cpholguera** [comment]
PR #1864 to be merged instead of this one due to inactivity and different location of content.

**Pull request closed without merging**
