### PR TITLE
Update excel based on restructured chapters#1254

### PR DESCRIPTION
**Pull request by A-AFTAHI**
Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR covers issue #< insert number here >.

### CODE REVIEW

**Comment by commjoen** [comment]
In 1.1.4 there is 1 slight change of wording for 1 of the requirements. As I have no computer with me .. but it should be an mstg issue as well. Maybe @sushi2k knows?

**Comment by A-AFTAHI** [comment]
As i mentioned to you and to @commjoen in slack. the excel links refer to the mstg and not masvs. so the variable used in the link will be changed to MSTG_VERSION instead of MASVS_VERSION. in addition as @commjoen  suggested i will add a new cell in the dashboard page to refer to the masvs version

**Comment by sushi2k** [comment]
> In 1.1.4 there is 1 slight change of wording for 1 of the requirements. As I have no computer with me .. but it should be an mstg issue as well. Maybe @sushi2k knows?

I was going through the commits in the MASVS and the issues in MSTG but couldn't find it. I remember also there was a slight change, but cannot remember where. I created a ticket https://github.com/OWASP/owasp-mstg/issues/1324. Might anyway be good to do a QA for this.

**Comment by sushi2k** [comment]
Thanks @A-AFTAHI. Nice work!

**Pull request merged**
