### PR TITLE
Added content for Sensitive Data in Backups and Keyboard Cache

### PR DESCRIPTION
**Pull request by kongwenbin**

### CODE REVIEW

**Comment by Sjord** [comment]
Maybe this is a useful resource in this context: [How do I prevent files from being backed up to iCloud and iTunes?](https://developer.apple.com/library/content/qa/qa1719/_index.html)

**Comment by b-mueller** [comment]
Thanks for adding the content re. backups Wen Bin! There is a separate test case for this though in the same file: "Testing for Sensitive Data in Backups". Can you move the info on backups to that other test case.

**Comment by kongwenbin** [comment]
I checked, the content were added to the "Testing for Sensitive Data in Backups" section. Do you mean another section?

**Comment by b-mueller** [comment]
@kongwenbin oops you're right, I mis-saw that :)

**Pull request merged**
