### PR TITLE
Add how to identify if a backup is encrypted

### PR DESCRIPTION
**Pull request by righettod**
Hi,

This PR add information about how to identify if a backup is encrypted or not.

- [x] Your contribution is written in the 2nd person (e.g. you)
- [x] Your contribution is written in an active present form for as much as possible.
- [x] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [x] Your contribution has proper formatted markdown and/or code
- [x] Any references to website have been formatted as [TEXT](URL “NAME”)
- [x] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

The LINKS checker failed, however, i did not add any links, so, I dit not have broken something with my PR I think 😄 

Thanks a lot in advance 😃

### CODE REVIEW

**Comment by cpholguera** [comment]
We'll take a look at that issue with the links, thanks for reporting it and for the PR :)

**Comment by cpholguera** [comment]
Google and Apple are causing us some trouble, some links do not exist anymore and others make the checker be trapped in a redirect loop. We'll try to find a solution for that and let you know ;)

**Comment by righettod** [comment]
Thanks a lot for the feedback.
Feel free to ping me if I need to change/clarify something in the PR 😃

**Review by cpholguera — APPROVED** [review]
Thanks for the addition @righettod! ;)

**Comment by righettod** [comment]
Thanks a lot for your feedback 💯

**Pull request merged**
