### PR TITLE
Add missing ticks (MSTG-STORAGE‑2 and MSTG-AUTH-4)

### PR DESCRIPTION
**Pull request by daMatz**
Thank you for submitting a Pull Request to the Mobile Security Testing Guide. Please make sure that:

- [ ] Your contribution is written in the 2nd person (e.g. you)
- [ ] Your contribution is written in an active present form for as much as possible.
- [ ] You have made sure that the reference section is up to date (e.g. please add sources you have used, make sure that the references to MITRE/MASVS/etc. are up to date)
- [ ] Your contribution has proper formatted markdown and/or code
- [ ] Any references to website have been formatted as [TEXT](URL “NAME”)
- [ ] You verified/tested the effectiveness of your contribution (e.g.: is the code really an effective remediation? Please verify it works!)

If your PR is related to an issue. Please end your PR test with the following line:
This PR closes #< insert number here >.

### CODE REVIEW

**Comment by cpholguera** [comment]
Hi @daMatz, could you please indicate what was the issue and what's what you did to fix it? Thanks in advance!

**Comment by daMatz** [comment]
> Hi @daMatz, could you please indicate what was the issue and what's what you did to fix it? Thanks in advance!

Hey! Sure!

Some test cases are part of level L1 / L2 and have colored cells (blue/green) but are missing the ticks ( :heavy_check_mark: )  in the excel sheets. I added them.

**Comment by cpholguera** [comment]
ok, thank you! We will check it out :)

**Comment by sushi2k** [comment]
Thanks @daMatz for your PR. We are trying to automate the checklist creation, see ticket: https://github.com/OWASP/owasp-mstg/issues/1837 

We are still looking for volunteers to support in that, to remove the manual work around this. If you are interested, please reach out to @cpholguera. Therefore we would close this PR and focus on the automated creation instead.

**Pull request closed without merging**
